---
# ------------------------------------------
# file: SDA_1_2_8/roles/design-network_settings-device_credentials/tasks/add_snmp_v3_credentials.yml
# ver: 1.2.0
# ansible ver: 2.7.8
# python ver: 2.7.15
# dna center ver: 1.2.8
# dna center rest api ver: 1.0.2
# author: Pradeep Singh (pradeesi@cisco.com)
# description: This task will add new snmpv3 credentials.
# DNAC Menu Path: Design --> Network Settings --> Device Credentials
# ------------------------------------------

  - name: "Add SNMPv3 Credentials"
    block:

      - name: "Check if SNMPv3 credentials already exist: {{ snmp_v3_item.name_description }}"
        include_tasks: get_global_credentials.yml

      - name: "Create SNMPv3 Credentials: {{ snmp_v3_item.name_description }}"
        block:
          - debug:
              var: "{{ lookup('template', 'generate_add_snmp_v3_credentials_body.j2') }}"
              verbosity: 1

          - name: "Invoke Create SNMPv3 Credentials API"
            uri:
              url: https://{{ dnac_credentials.ip_add }}/dna/intent/api/v1/global-credential/snmpv3
              method: POST
              validate_certs: no
              headers:
                X-Auth-Token: "{{ token.json.Token }}"
                Content-Type: 'application/json'
              body_type: json
              body: "{{ lookup('template', 'generate_add_snmp_v3_credentials_body.j2') }}"
              status_code: 202
            register: add_snmpv3_response

          - name: Check Create SNMPv3 Credentials Task Status
            include_role:
              name: get_task_status_v2
            vars:
              dnac_task_name: "Create SNMPv3 Credentials: {{ snmp_v3_item.name_description }}"
              dnac_task_id: "{{ add_snmpv3_response.json.response.taskId }}"

        when:
          - global_credential_id == ''

      - name: "Already exists?"
        debug:
            msg: "SNMPv3 Credentials already exist: {{ snmp_v3_item.name_description }}"
            verbosity: 0
        when:
          - global_credential_id != ''

    when:
      - snmp_v3_item.name_description is defined