---
# ------------------------------------------
# file: SDA_1_2_8/roles/design-network_settings-device_credentials/tasks/delete_global_credentials.yml
# ver: 1.2.0
# ansible ver: 2.7.8
# python ver: 2.7.15
# dna center ver: 1.2.8
# dna center rest api ver: 1.0.2
# author: Pradeep Singh (pradeesi@cisco.com)
# description: This task will delete the global device credentials.
# DNAC Menu Path: Design --> Network Settings --> Device Credentials
# ------------------------------------------

  - name: "Delete Credentials"
    block:

      - name: "Check if Credential already exist: {{ key_field_value }}"
        include_tasks: get_global_credentials.yml

      - name: "Delete Global Credential: {{ key_field_value }}"
        block:
          - name: "Invoke Delete Global Credential API"
            uri:
              url: https://{{ dnac_credentials.ip_add }}/dna/intent/api/v1/global-credential/{{ global_credential_id }}
              method: DELETE
              validate_certs: no
              headers:
                X-Auth-Token: "{{ token.json.Token }}"
                Content-Type: 'application/json'
              status_code: 202
            register: delete_global_credential_response


          - name: Check Delete Global Credential Task Status
            include_role:
              name: get_task_status_v2
            vars:
              dnac_task_name: "Delete Global Credential: {{ key_field_value }}"
              dnac_task_id: "{{ delete_global_credential_response.json.response.taskId }}"

        when:
          - global_credential_id != ''

      - name: "Doesn't exist?"
        debug:
            msg: "Global Credential doesn't exist: {{ key_field_value }}"
            verbosity: 0
        when:
          - global_credential_id == ''

    when:
      - key_field_name is defined
      - key_field_value is defined
      - credential_sub_type is defined