---
# ------------------------------------------
# file: SDA_1_2_8/roles/network_discovery/tasks/get_global_credentials_id.yml
# ver: 1.2.0
# ansible ver: 2.7.8
# python ver: 2.7.15
# dna center ver: 1.2.8
# dna center rest api ver: 1.0.2
# author: Pradeep Singh (pradeesi@cisco.com)
# description: This task will fetch device global credential IDs.
# DNAC Menu Path: None (Home Page Tools Section)
# ------------------------------------------

  - name: "Get Global Credential IDs"
    block:
      - name: "Get Credential Details for: {{ key_field_values }}"
        uri:
          url: https://{{ dnac_credentials.ip_add }}/dna/intent/api/v1/global-credential?credentialSubType={{ credential_sub_type }}
          method: GET
          validate_certs: no
          headers:
            X-Auth-Token: "{{ token.json.Token }}"
            Content-Type: 'application/json'
          status_code: 200
        register: get_global_credential_response

      - name: Filter Global Credential IDs and merge to the existing globalCredentialIdList
        set_fact:
          globalCredentialIdList: "{{ globalCredentialIdList }} +  {{ get_global_credential_response.json.response| selectattr( key_field_name , 'equalto', key_value )| map(attribute='id') | list }}"
        with_items: "{{ key_field_values }}"
        loop_control:
          loop_var: key_value

      - name: Key Field Name
        debug:
          var: key_field_name
          verbosity: 1

      - name: Key Field value
        debug:
          var: key_field_values
          verbosity: 1

      - name: Key Field value
        debug:
          var: globalCredentialIdList
          verbosity: 0

    when:
      - key_field_name is defined
      - key_field_values is defined
      - credential_sub_type is defined